blank_issues_enabled: false
contact_links:
  - name: Sigurnosna prijava
    url: https://github.com/bren-wp/by-ftp/security/policy
    about: Za osjetljive ranjivosti koristite sigurnosnu politiku umjesto javnog issuea.
