name: Prijedlog funkcije
description: Predložite fokusirano poboljšanje ByFTP-a
title: "[Prijedlog] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem ili radni tijek
      description: Koji bi radni tijek ovo poboljšalo?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Predloženo ponašanje
    validations:
      required: true
  - type: checkboxes
    id: constraints
    attributes:
      label: Ograničenja projekta
      options:
        - label: Prijedlog ne zahtijeva telemetriju niti slanje korisničkih podataka trećim stranama.
          required: true
